-- ══════════════════════════════════════════════════════════════════════
--  criar_tabelas.sql — Recria ANL_IA e CUBO_IA no BigQuery
--  Execute diretamente no console BQ ou via bq CLI:
--    bq query --use_legacy_sql=false < scripts/criar_tabelas.sql
-- ══════════════════════════════════════════════════════════════════════

CREATE OR REPLACE TABLE `meli-bi-data.SBOX_CREDITSTC.CARTAO_EXPIRADO_ANL_IA` AS
WITH

CARD_FISICA AS (
    SELECT
      c.CUS_CUST_ID,
      c.CARD_EXPIRATION_MONTH,
      c.CARD_EXPIRATION_YEAR,
      "FISICA" AS PRODUCT,
      CASE WHEN (c.CARD_EXPIRATION_MONTH < 10)
        THEN CONCAT(c.CARD_EXPIRATION_YEAR,"-0",c.CARD_EXPIRATION_MONTH)
        ELSE CONCAT(c.CARD_EXPIRATION_YEAR,"-",c.CARD_EXPIRATION_MONTH)
      END AS EXPIRATION_DATE,
      c.CARD_ID AS CARD_ID,
      a.CARD_ISS_ACC_ID AS DEBIT_CARD_NUMBER_ID,
      c.CARD_STATUS_INTERNAL_NAME,
      c.CARD_STATUS_USER_PREFERENCE_NAME,
      c.CARD_STATUS_USER_PREFERENCE_REASON,
      CASE WHEN (c.CARD_EXPIRATION_MONTH < 10)
        THEN CONCAT(c.CARD_EXPIRATION_YEAR,"-0",c.CARD_EXPIRATION_MONTH,"-01")
        ELSE CONCAT(c.CARD_EXPIRATION_YEAR,"-",c.CARD_EXPIRATION_MONTH,"-01")
      END AS TIM_MONTH2
    FROM `WHOWNER.LK_MP_CARD` c
    INNER JOIN `WHOWNER.BT_MP_CARD_ISSUER_ACCOUNTS` a
      ON a.CARD_ID = c.CARD_ID AND a.CARD_ISS_ACC_MODE = 'debit'
    WHERE c.SIT_SITE_ID = "MLB"
      AND c.CARD_BUSINESS_MODE = 'hybrid'
      AND c.CARD_EXPIRATION_YEAR IN (2025, 2026)
      AND (c.CARD_TERMINATION_DT >= DATE(CAST(CARD_EXPIRATION_YEAR AS INT64), CAST(CARD_EXPIRATION_MONTH AS INT64), 1)
        OR (c.CARD_STATUS_INTERNAL_NAME != 'terminated' AND c.CARD_STATUS_USER_PREFERENCE_NAME != 'terminated'))
),

DEBITO AS (
  SELECT
    t.DBT_CARD_ID,
    COUNT(*) AS QTD_DEB
  FROM CARD_FISICA u
  INNER JOIN `WHOWNER.BT_DBT_TRANSACTIONS` t ON u.DEBIT_CARD_NUMBER_ID = t.DBT_CARD_ID
  WHERE SIT_SITE_ID = 'MLB'
    AND DBT_TYPE = 'authorization'
    AND DBT_STATUS = 'approved'
    AND DBT_CARD_PRODUCT_TYPE = "hybrid"
    AND CASE
      WHEN DATE_SUB(DATE(CAST(CARD_EXPIRATION_YEAR AS INT64), CAST(CARD_EXPIRATION_MONTH AS INT64), 1), INTERVAL -1 MONTH) IN ("2025-05-01","2025-06-01","2025-07-01") THEN
        DBT_CREATION_DATETIME >= DATE_SUB(DATE(CAST(CARD_EXPIRATION_YEAR AS INT64), CAST(CARD_EXPIRATION_MONTH AS INT64), 1), INTERVAL 6 MONTH)
        AND DBT_CREATION_DATETIME < DATE(CAST(CARD_EXPIRATION_YEAR AS INT64), CAST(CARD_EXPIRATION_MONTH AS INT64), 1)
      WHEN DATE_SUB(DATE(CAST(CARD_EXPIRATION_YEAR AS INT64), CAST(CARD_EXPIRATION_MONTH AS INT64), 1), INTERVAL -1 MONTH) IN ("2025-08-01") THEN
        DBT_CREATION_DATETIME >= DATE_SUB(DATE(CAST(CARD_EXPIRATION_YEAR AS INT64), CAST(CARD_EXPIRATION_MONTH AS INT64), 1), INTERVAL 7 MONTH)
        AND DBT_CREATION_DATETIME < DATE_SUB(DATE(CAST(CARD_EXPIRATION_YEAR AS INT64), CAST(CARD_EXPIRATION_MONTH AS INT64), 1), INTERVAL 1 MONTH)
      ELSE
        DBT_CREATION_DATETIME >= DATE_SUB(DATE(CAST(CARD_EXPIRATION_YEAR AS INT64), CAST(CARD_EXPIRATION_MONTH AS INT64), 1), INTERVAL 8 MONTH)
        AND DBT_CREATION_DATETIME < DATE_SUB(DATE(CAST(CARD_EXPIRATION_YEAR AS INT64), CAST(CARD_EXPIRATION_MONTH AS INT64), 1), INTERVAL 2 MONTH)
    END
  GROUP BY 1
),

CREDITO AS (
  SELECT
    u.*,
    a.CCARD_ACCOUNT_STATUS,
    CASE WHEN a.CUS_CUST_ID IS NOT NULL THEN 'CRED' END AS FLAG_CRED,
    t.QTD_DEB
  FROM CARD_FISICA u
  LEFT JOIN `meli-bi-data.WHOWNER.BT_CCARD_CADASTRAL` a
    ON u.CUS_CUST_ID = a.CUS_CUST_ID
    AND CASE
      WHEN DATE_SUB(DATE(CAST(CARD_EXPIRATION_YEAR AS INT64), CAST(CARD_EXPIRATION_MONTH AS INT64), 1), INTERVAL -1 MONTH) IN ("2025-05-01","2025-06-01","2025-07-01") THEN
        FORMAT_DATE('%Y%m',TIM_MONTH) = FORMAT_DATE('%Y%m',DATE_SUB(DATE(CAST(CARD_EXPIRATION_YEAR AS INT64), CAST(CARD_EXPIRATION_MONTH AS INT64), 1), INTERVAL 1 MONTH))
      WHEN DATE_SUB(DATE(CAST(CARD_EXPIRATION_YEAR AS INT64), CAST(CARD_EXPIRATION_MONTH AS INT64), 1), INTERVAL -1 MONTH) IN ("2025-08-01") THEN
        FORMAT_DATE('%Y%m',TIM_MONTH) = FORMAT_DATE('%Y%m',DATE_SUB(DATE(CAST(CARD_EXPIRATION_YEAR AS INT64), CAST(CARD_EXPIRATION_MONTH AS INT64), 1), INTERVAL 2 MONTH))
      ELSE
        FORMAT_DATE('%Y%m',TIM_MONTH) = FORMAT_DATE('%Y%m',DATE_SUB(DATE(CAST(CARD_EXPIRATION_YEAR AS INT64), CAST(CARD_EXPIRATION_MONTH AS INT64), 1), INTERVAL 3 MONTH))
    END
    AND SIT_SITE_ID = 'MLB'
  LEFT JOIN DEBITO t ON t.DBT_CARD_ID = u.DEBIT_CARD_NUMBER_ID
),

ATV_TC AS (
  SELECT DISTINCT
    SAFE_CAST(CUS_CUST_ID AS INT64) AS CUS_CUST_ID,
    SAFE_CAST(CCARD_PURCH_OP_DT AS DATE) AS DT_USO_TC
  FROM `meli-bi-data.WHOWNER.BT_CCARD_PURCHASE`
  WHERE CCARD_PURCH_OP_STATUS IN ('normal','pending','processed','partially_confirmed')
    AND SIT_SITE_ID = 'MLB'
    AND CCARD_PURCH_OP_CARD_TYPE IN ('contactless','physical')
  QUALIFY ROW_NUMBER() OVER (PARTITION BY CUS_CUST_ID ORDER BY CCARD_PURCH_OP_DT DESC) = 1
),

ATV_TD AS (
  SELECT DISTINCT
    T.CUS_CUST_ID,
    CAST(T.DBT_CREATION_DATETIME AS DATE) AS DT_USO_TD
  FROM `WHOWNER.BT_DBT_TRANSACTIONS` T
  LEFT JOIN `WHOWNER.BT_MP_CARD_ISSUER_ACCOUNTS` CIA ON T.DBT_CARD_ID = CIA.CARD_ISS_ACC_ID
  LEFT JOIN `WHOWNER.LK_MP_CARD` C ON C.CARD_ID = CIA.CARD_ID
  WHERE T.dbt_type = 'authorization'
    AND T.sit_site_id IN ('MLB')
    AND T.DBT_STATUS = 'approved'
    AND T.DBT_SUBTYPE IN ('purchase')
    AND T.dbt_income_channel = 'transactional'
    AND C.CARD_STATUS_INTERNAL_REASON NOT LIKE '%deprecated%'
    AND CARD_TYPE_GROUP IN ('FISICA_DEBITO_HIBRIDA')
    AND T.CUS_CUST_ID NOT IN (SELECT CUS_CUST_ID FROM `meli-bi-data.WHOWNER.LK_CUS_CUSTOMERS_T`)
  QUALIFY ROW_NUMBER() OVER (PARTITION BY CUS_CUST_ID ORDER BY DBT_CREATION_DATETIME DESC) = 1
),

ATV_PROD AS (
  SELECT DISTINCT
    CUS_CUST_ID,
    DT_USO_PROD
  FROM (
    SELECT ATV_TD.CUS_CUST_ID, ATV_TD.DT_USO_TD AS DT_USO_PROD FROM ATV_TD
    UNION ALL
    SELECT ATV_TC.CUS_CUST_ID, ATV_TC.DT_USO_TC AS DT_USO_PROD FROM ATV_TC
  )
  QUALIFY ROW_NUMBER() OVER (PARTITION BY CUS_CUST_ID ORDER BY DT_USO_PROD DESC) = 1
),

RENOVADOS AS (
  SELECT DISTINCT
    CUS_CUST_ID,
    FORMAT_DATE('%d', CREATE_DATE) AS DIA_RENOVACAO,
    CAST(CREATE_DATE AS DATE) AS DT_RENOVACAO,
    CASE
      WHEN DELIVERED_DATE IS NULL THEN '00. CARTAO NAO ENTREGUE'
      WHEN DATE_DIFF(CAST(DELIVERED_DATE AS DATE), CAST(CREATE_DATE AS DATE), DAY) <= 2  THEN '01. ATE 2 DIAS'
      WHEN DATE_DIFF(CAST(DELIVERED_DATE AS DATE), CAST(CREATE_DATE AS DATE), DAY) <= 5  THEN '02. ATE 5 DIAS'
      WHEN DATE_DIFF(CAST(DELIVERED_DATE AS DATE), CAST(CREATE_DATE AS DATE), DAY) <= 7  THEN '03. ATE 7 DIAS'
      WHEN DATE_DIFF(CAST(DELIVERED_DATE AS DATE), CAST(CREATE_DATE AS DATE), DAY) <= 10 THEN '04. ATE 10 DIAS'
      ELSE '05. ACIMA DE 10 DIAS'
    END AS DIAS_ENTREGA,
    DATE_DIFF(CAST(DELIVERED_DATE AS DATE), CAST(CREATE_DATE AS DATE), DAY) as DIAS_ENTREGA_v2,
    CASE WHEN DELIVERED_DATE IS NOT NULL THEN 'ENTREGUE' ELSE 'NAO ENTREGUE' END AS FLAG_ENTREGA,
    CASE WHEN UNBLOCKED_DATE IS NOT NULL THEN 'DESBLOQUEADO' ELSE 'BLOQUEADO' END AS FLAG_BLOQUEIO,
    SHIPPING_STATUS_ID AS STATUS_ENTREGA
  FROM `meli-bi-data.WHOWNER.LK_MP_CARDS_TRACKING` T
  WHERE EXTRACT(YEAR FROM T.CREATE_DATE) IN (2025, 2026)
    AND CAST(T.CREATE_DATE AS DATE) >= '2025-03-01'
    AND SIT_SITE_ID = "MLB"
    AND DBT_CARD_REQ_ACQUISITON_FLOW = "renewal"
    AND CARD_TYPE_GROUP = "FISICA_DEBITO_HIBRIDA"
  QUALIFY ROW_NUMBER() OVER (PARTITION BY CUS_CUST_ID ORDER BY CREATE_DATE DESC) = 1
),

REEMITIDOS AS (
  SELECT DISTINCT
    CUS_CUST_ID,
    CAST(CREATE_DATE AS DATE) AS DT_REEMITIDOS,
    CASE
      WHEN DELIVERED_DATE IS NULL THEN '00. CARTAO NAO ENTREGUE'
      WHEN DATE_DIFF(CAST(DELIVERED_DATE AS DATE), CAST(CREATE_DATE AS DATE), DAY) <= 2  THEN '01. ATE 2 DIAS'
      WHEN DATE_DIFF(CAST(DELIVERED_DATE AS DATE), CAST(CREATE_DATE AS DATE), DAY) <= 5  THEN '02. ATE 5 DIAS'
      WHEN DATE_DIFF(CAST(DELIVERED_DATE AS DATE), CAST(CREATE_DATE AS DATE), DAY) <= 7  THEN '03. ATE 7 DIAS'
      WHEN DATE_DIFF(CAST(DELIVERED_DATE AS DATE), CAST(CREATE_DATE AS DATE), DAY) <= 10 THEN '04. ATE 10 DIAS'
      ELSE '05. ACIMA DE 10 DIAS'
    END AS DIAS_ENTREGA,
    DATE_DIFF(CAST(DELIVERED_DATE AS DATE), CAST(CREATE_DATE AS DATE), DAY) as DIAS_ENTREGA_v2,
    CASE WHEN DELIVERED_DATE IS NOT NULL THEN 'ENTREGUE' ELSE 'NAO ENTREGUE' END AS FLAG_ENTREGA,
    CASE WHEN UNBLOCKED_DATE IS NOT NULL THEN 'DESBLOQUEADO' ELSE 'BLOQUEADO' END AS FLAG_BLOQUEIO,
    SHIPPING_STATUS_ID AS STATUS_ENTREGA
  FROM `meli-bi-data.WHOWNER.LK_MP_CARDS_TRACKING` T
  WHERE EXTRACT(YEAR FROM T.CREATE_DATE) IN (2025, 2026)
    AND CAST(T.CREATE_DATE AS DATE) >= '2025-05-01'
    AND SIT_SITE_ID = "MLB"
    AND TIPO_FLOW = "REISSUE"
    AND CARD_TYPE_GROUP = "FISICA_DEBITO_HIBRIDA"
  QUALIFY ROW_NUMBER() OVER (PARTITION BY CUS_CUST_ID ORDER BY CREATE_DATE DESC) = 1
),

ADQ_TC AS (
  SELECT DISTINCT
    CUS_CUST_ID,
    CASE WHEN (CCARD_GLOBAL_LIMIT_AMT_LC <= 100 OR ccard_product_id = 5) THEN '01. MICRO TC' ELSE '02. TC FULL' END AS TP_CARTAO_TC,
    CASE
      WHEN CCARD_PROP_STATUS = 'accepted' THEN '01. CONVERTIDO'
      WHEN CCARD_PROP_STATUS = 'pending'  THEN '02. ENCENDIDO'
      ELSE '03. CANCELADO'
    END AS STATUS_PROPOSTA_TC
  FROM `meli-bi-data.WHOWNER.BT_CCARD_PROPOSAL`
  WHERE SIT_SITE_ID LIKE '%MLB%'
  QUALIFY ROW_NUMBER() OVER (PARTITION BY CUS_CUST_ID ORDER BY CCARD_PROP_UPDATE_DT DESC) = 1
),

TRANS_NEG AS (
  SELECT
    A.CUS_CUST_ID,
    A.SAFRA,
    B.DT_NEGATIVA,
    B.MOTIVO_NEGATIVA,
    B.TPV_NEGATIVA
  FROM (
    SELECT *, CONCAT(LEFT(EXPIRATION_DATE,4), RIGHT(EXPIRATION_DATE,2)) AS SAFRA
    FROM `meli-bi-data.SBOX_CREDITSTC.CARD_FISICA_EXPIRADOS_J`
    QUALIFY ROW_NUMBER() OVER (PARTITION BY CUS_CUST_ID ORDER BY EXPIRATION_DATE ASC) = 1
  ) AS A
  LEFT JOIN (
    SELECT DISTINCT
      'NEGATIVA TC' AS FLAG_BASE,
      CUS_CUST_ID,
      CAST(CCARD_CONSUMP_CREATION_DATETIME AS DATE) AS DT_NEGATIVA,
      COALESCE(auth.APPROVAL.REASON, 'OUTRO') AS MOTIVO_NEGATIVA,
      CCARD_CONSUMP_OPERATION.TOTAL.AMT AS TPV_NEGATIVA
    FROM `meli-bi-data.WHOWNER.BT_CCARD_MONZA_CONSUMPTIONS`
    LEFT JOIN UNNEST(CCARD_CONSUMP_AUTHS) AS auth
    WHERE SIT_SITE_ID = 'MLB'
      AND DATE_TRUNC(CCARD_CONSUMP_CREATION_DATETIME, MONTH) >= "2025-01-01"
      AND CCARD_CONSUMP_STATUS IN ("cancelled","rejected","reversed")

    UNION ALL

    SELECT DISTINCT
      'NEGATIVA TD' AS FLAG_BASE,
      T.CUS_CUST_ID,
      CAST(DBT_CREATION_DATETIME AS DATE) AS DT_NEGATIVA,
      COALESCE(DBT_STATUS_DETAIL, 'OUTRO') AS MOTIVO_NEGATIVA,
      T.DBT_TRANSACTION_TOTAL_AMOUNT AS TPV_NEGATIVA
    FROM `meli-bi-data.WHOWNER.BT_DBT_TRANSACTIONS` T
    LEFT JOIN `meli-bi-data.WHOWNER.BT_MP_CARD_ISSUER_ACCOUNTS` CIA ON T.DBT_CARD_ID = CIA.CARD_ISS_ACC_ID
    LEFT JOIN `meli-bi-data.WHOWNER.LK_MP_CARD` C ON C.CARD_ID = CIA.CARD_ID
    WHERE T.dbt_type = 'authorization'
      AND DBT_STATUS IN ('declined')
      AND DBT_SUBTYPE IN ('purchase','withdraw')
      AND T.sit_site_id IN ('MLB')
      AND T.dbt_income_channel = 'transactional'
      AND C.CARD_STATUS_INTERNAL_REASON NOT LIKE '%deprecated%'
      AND FORMAT_DATE("%Y%m", DBT_CREATION_DATETIME) >= '202503'
  ) B ON A.CUS_CUST_ID = B.CUS_CUST_ID
  LEFT JOIN (
    SELECT DISTINCT CUS_CUST_ID
    FROM `meli-bi-data.WHOWNER.LK_MP_CARDS_TRACKING`
    WHERE EXTRACT(YEAR FROM CREATE_DATE) IN (2025, 2026)
      AND CAST(CREATE_DATE AS DATE) >= '2025-04-01'
      AND SIT_SITE_ID = "MLB"
      AND DBT_CARD_REQ_ACQUISITON_FLOW = "renewal"
      AND CARD_TYPE_GROUP = "FISICA_DEBITO_HIBRIDA"
  ) AS REN ON A.CUS_CUST_ID = REN.CUS_CUST_ID
  WHERE REN.CUS_CUST_ID IS NULL
    AND A.SAFRA = FORMAT_DATE('%Y%m', (B.DT_NEGATIVA - INTERVAL 1 MONTH))
  QUALIFY ROW_NUMBER() OVER (PARTITION BY A.CUS_CUST_ID ORDER BY B.DT_NEGATIVA ASC) = 1
),

MAPA_CLI AS (
  SELECT DISTINCT
    CUS_CUST_ID,
    TIM_MONTH,
    FL_ACIONAVEL AS MAPA_PORTFOLIO
  FROM `meli-bi-data.SBOX_CREDITSTC.MAPA_PORTIFOLIO_ANALITICO`
  WHERE FL_CANCELADO = 0 AND FL_BASE_LIQUIDA_REF = 1
  QUALIFY ROW_NUMBER() OVER (PARTITION BY CUS_CUST_ID ORDER BY TIM_MONTH DESC) = 1
),

SELLER AS (
  SELECT DISTINCT
    CUS_CUST_ID,
    CUST_TYPE_GESTION AS SEGMENT
  FROM `meli-bi-data.WHOWNER.LK_MP_MAUS_SEGMENTATION`
  WHERE SIT_SITE_ID = 'MLB'
    AND CUST_TYPE_GESTION <> 'INACTIVO'
    AND FORMAT_DATE("%Y%m", PHOTO_ID) = FORMAT_DATE('%Y%m', (CURRENT_DATE - INTERVAL 1 MONTH))
  QUALIFY ROW_NUMBER() OVER (PARTITION BY CUS_CUST_ID, FORMAT_DATE("%Y%m", PHOTO_ID) ORDER BY PHOTO_ID DESC) = 1
),

TPV_TC_PRE AS (
  SELECT
    cf.CUS_CUST_ID,
    SUM(p.ccard_purch_op_amt_lc) AS TPV_TC_PRE
  FROM CARD_FISICA cf
  INNER JOIN `meli-bi-data.WHOWNER.BT_CCARD_PURCHASE` p
    ON cf.CUS_CUST_ID = SAFE_CAST(p.CUS_CUST_ID AS INT64)
    AND CAST(p.CCARD_PURCH_OP_DT AS DATE) BETWEEN
        DATE_SUB(DATE(CONCAT(cf.EXPIRATION_DATE, '-01')), INTERVAL 90 DAY)
        AND DATE(CONCAT(cf.EXPIRATION_DATE, '-01'))
  WHERE p.SIT_SITE_ID = 'MLB'
    AND p.CCARD_PURCH_OP_STATUS IN ('normal','pending','processed','partially_confirmed')
    AND p.CCARD_PURCH_OP_CARD_TYPE IN ('contactless','physical')
  GROUP BY 1
),

TPV_TD_PRE AS (
  SELECT
    cf.CUS_CUST_ID,
    SUM(t.DBT_BILLING_AMOUNT) AS TPV_TD_PRE
  FROM CARD_FISICA cf
  INNER JOIN `meli-bi-data.WHOWNER.BT_DBT_TRANSACTIONS` t
    ON cf.CUS_CUST_ID = t.CUS_CUST_ID
    AND CAST(t.DBT_CREATION_DATETIME AS DATE) BETWEEN
        DATE_SUB(DATE(CONCAT(cf.EXPIRATION_DATE, '-01')), INTERVAL 90 DAY)
        AND DATE(CONCAT(cf.EXPIRATION_DATE, '-01'))
  WHERE t.SIT_SITE_ID = 'MLB'
    AND t.DBT_TYPE = 'authorization'
    AND t.DBT_STATUS = 'approved'
    AND t.DBT_SUBTYPE = 'purchase'
  GROUP BY 1
),

TPV_TC_POS AS (
  SELECT
    r.CUS_CUST_ID,
    SUM(p.ccard_purch_op_amt_lc) AS TPV_TC_POS
  FROM RENOVADOS r
  INNER JOIN `meli-bi-data.WHOWNER.BT_CCARD_PURCHASE` p
    ON r.CUS_CUST_ID = SAFE_CAST(p.CUS_CUST_ID AS INT64)
    AND CAST(p.CCARD_PURCH_OP_DT AS DATE) BETWEEN r.DT_RENOVACAO
        AND DATE_ADD(r.DT_RENOVACAO, INTERVAL 90 DAY)
  WHERE p.SIT_SITE_ID = 'MLB'
    AND p.CCARD_PURCH_OP_STATUS IN ('normal','pending','processed','partially_confirmed')
    AND p.CCARD_PURCH_OP_CARD_TYPE IN ('contactless','physical')
  GROUP BY 1
),

TPV_TD_POS AS (
  SELECT
    r.CUS_CUST_ID,
    SUM(t.DBT_BILLING_AMOUNT) AS TPV_TD_POS
  FROM RENOVADOS r
  INNER JOIN `meli-bi-data.WHOWNER.BT_DBT_TRANSACTIONS` t
    ON r.CUS_CUST_ID = t.CUS_CUST_ID
    AND CAST(t.DBT_CREATION_DATETIME AS DATE) BETWEEN r.DT_RENOVACAO
        AND DATE_ADD(r.DT_RENOVACAO, INTERVAL 90 DAY)
  WHERE t.SIT_SITE_ID = 'MLB'
    AND t.DBT_TYPE = 'authorization'
    AND t.DBT_STATUS = 'approved'
    AND t.DBT_SUBTYPE = 'purchase'
  GROUP BY 1
)

-- ── SELECT FINAL ──────────────────────────────────────────────

SELECT DISTINCT
  (CURRENT_DATE - 1)                                      AS DT_ATUALIZACAO,
  CARD_FISICA.CUS_CUST_ID,
  LEFT(CARD_FISICA.EXPIRATION_DATE, 4)                    AS ANO_EXPIRATION,
  CARD_FISICA.EXPIRATION_DATE,
  CARD_FISICA.PRODUCT,
  RENOVADOS.DIAS_ENTREGA,
  COALESCE(RENOVADOS.DIAS_ENTREGA_V2, REEMITIDOS.DIAS_ENTREGA_V2)   AS DIAS_ENTREGA_V2,
  CASE WHEN (CREDITO.CCARD_ACCOUNT_STATUS = 'active' OR QTD_DEB IS NOT NULL)
    THEN 'GRUPO1' ELSE 'GRUPO2'
  END AS FLAG_GRUPO,
  CASE WHEN CREDITO.FLAG_CRED = 'CRED' THEN '01. CREDITO' ELSE '02. DEBITO' END AS FLAG_PROD,
  COALESCE(RENOVADOS.DT_RENOVACAO, REEMITIDOS.DT_REEMITIDOS)   AS DT_RENOVACAO_REEMISSAO,
  RENOVADOS.DT_RENOVACAO,
  REEMITIDOS.DT_REEMITIDOS,
  RENOVADOS.STATUS_ENTREGA                                AS RENOVADOS_STATUS_ENTREGA,
  REEMITIDOS.STATUS_ENTREGA                               AS REEMITIDOS_STATUS_ENTREGA,
  ATV_PROD.DT_USO_PROD,
  COALESCE(RENOVADOS.FLAG_BLOQUEIO, REEMITIDOS.FLAG_BLOQUEIO)   AS FLAG_BLOQUEIO,
  COALESCE(SELLER.SEGMENT, 'INDIVIDUO')                   AS FLAG_SELLER,
  CASE
    WHEN DATE_DIFF(CURRENT_DATE, ATV_TD.DT_USO_TD, DAY) <= 30  THEN '01. 1 A 30 D'
    WHEN DATE_DIFF(CURRENT_DATE, ATV_TD.DT_USO_TD, DAY) <= 60  THEN '02. 31 A 60 D'
    WHEN DATE_DIFF(CURRENT_DATE, ATV_TD.DT_USO_TD, DAY) <= 90  THEN '03. 61 A 90 D'
    WHEN DATE_DIFF(CURRENT_DATE, ATV_TD.DT_USO_TD, DAY) <= 120 THEN '04. 91 A 120 D'
    WHEN DATE_DIFF(CURRENT_DATE, ATV_TD.DT_USO_TD, DAY) <= 180 THEN '05. 121 A 180 D'
    WHEN DATE_DIFF(CURRENT_DATE, ATV_TD.DT_USO_TD, DAY) > 180  THEN '06. ACIMA DE 180 D'
    WHEN QTD_DEB IS NOT NULL                                    THEN '06. ACIMA DE 180 D'
    ELSE '07. NAO ATIVO'
  END AS FLAG_CICLO_USO_TD,
  CASE
    WHEN DATE_DIFF(CURRENT_DATE, ATV_PROD.DT_USO_PROD, DAY) <= 30  THEN '01. 1 A 30 D'
    WHEN DATE_DIFF(CURRENT_DATE, ATV_PROD.DT_USO_PROD, DAY) <= 60  THEN '02. 31 A 60 D'
    WHEN DATE_DIFF(CURRENT_DATE, ATV_PROD.DT_USO_PROD, DAY) <= 90  THEN '03. 61 A 90 D'
    WHEN DATE_DIFF(CURRENT_DATE, ATV_PROD.DT_USO_PROD, DAY) <= 120 THEN '04. 91 A 120 D'
    WHEN DATE_DIFF(CURRENT_DATE, ATV_PROD.DT_USO_PROD, DAY) <= 180 THEN '05. 121 A 180 D'
    WHEN DATE_DIFF(CURRENT_DATE, ATV_PROD.DT_USO_PROD, DAY) > 180  THEN '06. ACIMA DE 180 D'
    WHEN (CREDITO.FLAG_CRED = 'CRED' OR QTD_DEB IS NOT NULL)       THEN '06. ACIMA DE 180 D'
    ELSE '07. NAO ATIVO'
  END AS FLAG_CICLO_USO_PROD,
  CASE WHEN (RENOVADOS.CUS_CUST_ID IS NULL AND REEMITIDOS.CUS_CUST_ID IS NULL) AND CREDITO.FLAG_CRED = 'CRED'
    THEN TRANS_NEG.MOTIVO_NEGATIVA ELSE 'SEM TRANSACAO NEGADA'
  END AS MOTIVO_NEGATIVA_TC,
  CASE WHEN (RENOVADOS.CUS_CUST_ID IS NULL AND REEMITIDOS.CUS_CUST_ID IS NULL) AND CREDITO.FLAG_CRED NOT IN ('CRED')
    THEN TRANS_NEG.MOTIVO_NEGATIVA ELSE 'SEM TRANSACAO NEGADA'
  END AS MOTIVO_NEGATIVA_TD,
  COALESCE(MAPA_CLI.MAPA_PORTFOLIO, '10) DEBITO')         AS MAPA_PORTFOLIO,

  -- TPV negativado
  SUM(TRANS_NEG.TPV_NEGATIVA)                             AS TPV_NEGATIVA,

  -- TPV pré-expiração (90d antes)
  COALESCE(MAX(TPV_TC_PRE.TPV_TC_PRE), 0)                 AS TPV_TC_PRE_EXP,
  COALESCE(MAX(TPV_TD_PRE.TPV_TD_PRE), 0)                 AS TPV_TD_PRE_EXP,

  -- TPV pós-renovação (90d depois)
  COALESCE(MAX(TPV_TC_POS.TPV_TC_POS), 0)                 AS TPV_TC_POS_REN,
  COALESCE(MAX(TPV_TD_POS.TPV_TD_POS), 0)                 AS TPV_TD_POS_REN,

  -- Flag ativo pós-renovação por produto
  CASE WHEN TPV_TC_POS.CUS_CUST_ID IS NOT NULL THEN 1 ELSE 0 END AS FLAG_ATIVO_TC_POS,
  CASE WHEN TPV_TD_POS.CUS_CUST_ID IS NOT NULL THEN 1 ELSE 0 END AS FLAG_ATIVO_TD_POS,

  -- ✅ NOVO: Flag ativo físico pós-renovação (TC OU TD — sem dupla contagem)
  CASE WHEN (TPV_TC_POS.CUS_CUST_ID IS NOT NULL OR TPV_TD_POS.CUS_CUST_ID IS NOT NULL)
    THEN 1 ELSE 0
  END AS FLAG_ATIVO_FISICO_POS,

  -- Contagens
  COUNT(DISTINCT CARD_FISICA.CUS_CUST_ID) AS QTDE_TOTAL,
  COUNT(DISTINCT CASE WHEN NOT (CARD_FISICA.EXPIRATION_DATE = "2025-05" AND RENOVADOS.DT_RENOVACAO = "2025-04-15")
    AND RENOVADOS.CUS_CUST_ID IS NOT NULL THEN CARD_FISICA.CUS_CUST_ID END) AS QTDE_RENOVADOS,
  COUNT(DISTINCT CASE WHEN ((CARD_FISICA.CARD_STATUS_USER_PREFERENCE_REASON = "renewed"
      OR CARD_FISICA.CARD_STATUS_USER_PREFERENCE_REASON = "disabled_by_new_activation")
      OR RENOVADOS.CUS_CUST_ID IS NOT NULL)
      AND (DATE_DIFF(CURRENT_DATE, RENOVADOS.DT_RENOVACAO, DAY) >= 10 OR DATE_DIFF(CURRENT_DATE, REEMITIDOS.DT_REEMITIDOS, DAY) >= 10)
      AND COALESCE(RENOVADOS.FLAG_ENTREGA, REEMITIDOS.FLAG_ENTREGA) = 'ENTREGUE'
    THEN CARD_FISICA.CUS_CUST_ID END) AS QTDE_ENTREGUE,
  COUNT(DISTINCT CASE WHEN ((CARD_FISICA.CARD_STATUS_USER_PREFERENCE_REASON = "renewed"
      OR CARD_FISICA.CARD_STATUS_USER_PREFERENCE_REASON = "disabled_by_new_activation")
      OR RENOVADOS.CUS_CUST_ID IS NOT NULL)
      AND (DATE_DIFF(CURRENT_DATE, RENOVADOS.DT_RENOVACAO, DAY) >= 10 OR DATE_DIFF(CURRENT_DATE, REEMITIDOS.DT_REEMITIDOS, DAY) >= 10)
      AND COALESCE(RENOVADOS.FLAG_BLOQUEIO, REEMITIDOS.FLAG_BLOQUEIO) = 'DESBLOQUEADO'
    THEN CARD_FISICA.CUS_CUST_ID END) AS QTDE_DESBLOQUEADO,
  COUNT(DISTINCT CASE WHEN REEMITIDOS.CUS_CUST_ID IS NOT NULL
      AND REEMITIDOS.DT_REEMITIDOS >= DATE_SUB(DATE(CONCAT(CARD_FISICA.EXPIRATION_DATE, '-01')), INTERVAL 1 MONTH)
      AND REEMITIDOS.DT_REEMITIDOS <= DATE_ADD(DATE(CONCAT(CARD_FISICA.EXPIRATION_DATE, '-01')), INTERVAL 2 MONTH)
    THEN CARD_FISICA.CUS_CUST_ID END) AS QTDE_REEMITIDOS,
  COUNT(DISTINCT CASE WHEN RENOVADOS.CUS_CUST_ID IS NULL OR REEMITIDOS.CUS_CUST_ID IS NULL
    THEN CARD_FISICA.CUS_CUST_ID END) AS QTDE_TRANS_NEGADA

FROM CARD_FISICA
LEFT JOIN ADQ_TC      ON CARD_FISICA.CUS_CUST_ID = ADQ_TC.CUS_CUST_ID
LEFT JOIN ATV_TC      ON CARD_FISICA.CUS_CUST_ID = ATV_TC.CUS_CUST_ID
LEFT JOIN ATV_TD      ON CARD_FISICA.CUS_CUST_ID = ATV_TD.CUS_CUST_ID
LEFT JOIN SELLER      ON CARD_FISICA.CUS_CUST_ID = SELLER.CUS_CUST_ID
LEFT JOIN CREDITO     ON CARD_FISICA.CUS_CUST_ID = CREDITO.CUS_CUST_ID
LEFT JOIN ATV_PROD    ON CARD_FISICA.CUS_CUST_ID = ATV_PROD.CUS_CUST_ID
LEFT JOIN RENOVADOS   ON CARD_FISICA.CUS_CUST_ID = RENOVADOS.CUS_CUST_ID
  AND RENOVADOS.DT_RENOVACAO <= DATE(
      EXTRACT(YEAR FROM PARSE_DATE('%Y-%m', CARD_FISICA.EXPIRATION_DATE)) + IF(EXTRACT(MONTH FROM PARSE_DATE('%Y-%m', CARD_FISICA.EXPIRATION_DATE)) = 12, 1, 0),
      IF(EXTRACT(MONTH FROM PARSE_DATE('%Y-%m', CARD_FISICA.EXPIRATION_DATE)) = 12, 1, EXTRACT(MONTH FROM PARSE_DATE('%Y-%m', CARD_FISICA.EXPIRATION_DATE)) + 1),
      1)
LEFT JOIN REEMITIDOS  ON CARD_FISICA.CUS_CUST_ID = REEMITIDOS.CUS_CUST_ID
  AND REEMITIDOS.DT_REEMITIDOS BETWEEN
      DATE_ADD(DATE(CONCAT(CARD_FISICA.EXPIRATION_DATE, '-01')), INTERVAL 1 MONTH)
      AND DATE_ADD(DATE(CONCAT(CARD_FISICA.EXPIRATION_DATE, '-01')), INTERVAL 2 MONTH)
LEFT JOIN TRANS_NEG   ON CARD_FISICA.CUS_CUST_ID = TRANS_NEG.CUS_CUST_ID
LEFT JOIN MAPA_CLI    ON CARD_FISICA.CUS_CUST_ID = MAPA_CLI.CUS_CUST_ID
  AND CAST(CARD_FISICA.TIM_MONTH2 AS DATE) = DATE_ADD(MAPA_CLI.TIM_MONTH, INTERVAL 1 MONTH)
LEFT JOIN TPV_TC_PRE  ON CARD_FISICA.CUS_CUST_ID = TPV_TC_PRE.CUS_CUST_ID
LEFT JOIN TPV_TD_PRE  ON CARD_FISICA.CUS_CUST_ID = TPV_TD_PRE.CUS_CUST_ID
LEFT JOIN TPV_TC_POS  ON CARD_FISICA.CUS_CUST_ID = TPV_TC_POS.CUS_CUST_ID
LEFT JOIN TPV_TD_POS  ON CARD_FISICA.CUS_CUST_ID = TPV_TD_POS.CUS_CUST_ID

GROUP BY ALL;


-- ── CUBO AGREGADO ─────────────────────────────────────────────

CREATE OR REPLACE TABLE `meli-bi-data.SBOX_CREDITSTC.CARTAO_EXPIRADO_CUBO_IA` AS (
  SELECT DISTINCT
    DT_ATUALIZACAO,
    ANO_EXPIRATION,
    EXPIRATION_DATE,
    PRODUCT,
    FLAG_PROD,
    FLAG_GRUPO,
    MAPA_PORTFOLIO,
    MOTIVO_NEGATIVA_TC,
    MOTIVO_NEGATIVA_TD,
    DIAS_ENTREGA_V2,
    FLAG_BLOQUEIO,
    COALESCE(RENOVADOS_STATUS_ENTREGA, 'pending') AS RENOVADOS_STATUS_ENTREGA,
    COALESCE(REEMITIDOS_STATUS_ENTREGA, 'pending') AS REEMITIDOS_STATUS_ENTREGA,
    FLAG_SELLER,
    FLAG_CICLO_USO_TD,
    FLAG_CICLO_USO_PROD,
    COALESCE(DIAS_ENTREGA, '06. NAO RENOVADO') AS DIAS_ENTREGA,
    SUM(TPV_NEGATIVA)          AS TPV_NEGATIVA,
    SUM(TPV_TC_PRE_EXP)        AS TPV_TC_PRE,
    SUM(TPV_TD_PRE_EXP)        AS TPV_TD_PRE,
    SUM(TPV_TC_POS_REN)        AS TPV_TC_POS,
    SUM(TPV_TD_POS_REN)        AS TPV_TD_POS,
    SUM(FLAG_ATIVO_TC_POS)     AS QTDE_ATIVO_TC,
    SUM(FLAG_ATIVO_TD_POS)     AS QTDE_ATIVO_TD,
    -- ✅ NOVO: ativos físicos pós-renovação (TC OU TD, sem dupla contagem)
    SUM(FLAG_ATIVO_FISICO_POS) AS QTDE_ATIVO_FISICO,
    SUM(QTDE_TOTAL)            AS QTDE_TOTAL,
    SUM(QTDE_RENOVADOS)        AS QTDE_RENOVADOS,
    SUM(QTDE_REEMITIDOS)       AS QTDE_REEMITIDOS,
    SUM(QTDE_ENTREGUE)         AS QTDE_ENTREGUE,
    SUM(QTDE_DESBLOQUEADO)     AS QTDE_DESBLOQUEADO,
    SUM(QTDE_TRANS_NEGADA)     AS QTDE_TRANS_NEGADA
  FROM `meli-bi-data.SBOX_CREDITSTC.CARTAO_EXPIRADO_ANL_IA`
  GROUP BY ALL
);
